### ISSUE TITLE
Can the automated docker build be restarted?

### ISSUE THREAD

**Issue by WesleyRosenblum** [marten-seemann/chrome-quic-interop-runner#5]
The Chrome docker image hasn't been updated in 10 months. 

I see the following message [here](https://github.com/marten-seemann/chrome-quic-interop-runner/actions/workflows/build.yml):

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

Also, the quic version needs to be updated to `h3` [here ](https://github.com/marten-seemann/chrome-quic-interop-runner/blob/661b06e99b3b30815829e99a4fb19f815670781c/run.py#L41)

Thanks!

**Comment by marten-seemann** [comment]
Want to send us a PR? I won’t have the bandwidth to continuously update this repo.

**Comment by WesleyRosenblum** [comment]
Sure! https://github.com/marten-seemann/chrome-quic-interop-runner/pull/6

**Comment by WesleyRosenblum** [comment]
Nice to see some green back for Chrome in the Interop Report: https://interop.seemann.io/?client=chrome&test=3
